### ISSUE TITLE
blacklist error tried with diferent user countries and tried with vpn

### ISSUE THREAD

**Issue by Liam942** [roju/tiktok-live-recorder#21]
Unrestricted country list: https://github.com/Michele0303/TikTok-Live-Recorder/edit/main/GUIDE.md#unrestricted-country
2023-12-14 22:34:11,266 - ERROR - Exception caught in main:
2023-12-14 22:34:11,267 - ERROR - Redirect

Traceback (most recent call last):
  File "C:\Users\hejsa\Downloads\tiktok-live-recorder\tiktok_bot.py", line 279, in get_room_id_from_user
    raise errors.Blacklisted('Redirect')
errors.Blacklisted: Redirect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hejsa\Downloads\tiktok-live-recorder\ttlr.py", line 103, in main
    bot.run()
  File "C:\Users\hejsa\Downloads\tiktok-live-recorder\tiktok_bot.py", line 87, in run
    raise e
  File "C:\Users\hejsa\Downloads\tiktok-live-recorder\tiktok_bot.py", line 48, in run
    self.room_id = self.get_room_id_from_user()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hejsa\Downloads\tiktok-live-recorder\tiktok_bot.py", line 285, in get_room_id_from_user
    raise errors.Blacklisted(e)
errors.Blacklisted: Redirect

**Comment by booleangit** [comment]
Same issue here!

**Comment by CyberbobGR** [comment]
I'm having the same problem.

**Comment by RealityQuizzicality** [comment]
i think its working with vpn set to USA Houston, TX

**Comment by Zopmozami** [comment]
Same error with v4.2, but it's work with v4.1

**Comment by booleangit** [comment]
> Same error with v4.2, but it's work with v4.1

Both don't work for me. It seems the default proxy (TOR) is also blocked by TikTok.

**Comment by RealityQuizzicality** [comment]
only working with American ip for me

**Comment by RealityQuizzicality** [comment]
> I put on american ip and tried to record american tiktokers and failed on them as well

im using Mullvad vpn

**Comment by Zopmozami** [comment]
v4.1 without vpn and proxy, it's ok for me (i'm using python 3.9.7)

![Live_recorder](https://github.com/roju/tiktok-live-recorder/assets/101194341/ac403b9f-de3d-4c0f-9c91-9d765df1c297)

**Comment by Zopmozami** [comment]
I now understand why it worked with this v4.1
I had included the cookie in the file "bot_utils.py"

**Comment by Zopmozami** [comment]
![Capture d’écran 2023-12-15 155840](https://github.com/roju/tiktok-live-recorder/assets/101194341/2a193af1-bef7-4cd3-b9dc-a61a8243c9d0)

**Comment by SuicidalOrchid** [comment]
> for me typing in feed/?aid makes nothing show up

Try typing just "feed" in Network search, it should show up as I also had the same problem, and don't forget to refresh page. By the way, you can access Cookies without going to Dev Console. You can install Cookie editor extensions on your supported browser, for example EditThisCookie on Chrome.

**Comment by SuicidalOrchid** [comment]
I'm also trying to get it to work, but where the hell is csrf_session_id located? Searched it in feed, Cookie editor, but still can't find it.

**Comment by fulopsoma23** [comment]
Yes, it worked, thank you!

It's important to look for the name feed/?WebldLastTime= in the network section. Copy all lines from the cookie section, not just csrf_session_id.

**Comment by SuicidalOrchid** [comment]
> Yes, it worked, thank you!
> 
> It's important to look for the name feed/?WebldLastTime= in the network section. Copy all lines from the cookie section, not just csrf_session_id.

Oh, I thought that I needed csrf_session_id which I couldn't find, but it works without it. Cheers!

**Comment by roberto-sartori-gl** [comment]
So do we need cookies now? Not the best news...

**Comment by booleangit** [comment]
> So do we need cookies now? Not the best news...

Indeed. You'd better start creating some burner accounts as I expect them to start blocking accounts very soon.

**Comment by roberto-sartori-gl** [comment]
> @roberto-sartori-gl @booleangit  Do you really understand how this works? 

Yes, do you?

The problem is not the account being banned, the problem is that cookies may became invalid, they change.
I have my tiktok-live scripts running automatically on an headless machine, if now I have to keep the cookies up to date, it will became much more complex to manage.

**Comment by roberto-sartori-gl** [comment]
> > > @roberto-sartori-gl @booleangit  Do you really understand how this works?
> > 
> > 
> > Yes, do you?
> > The problem is not the account being banned, the problem is that cookies may become invalid. I have my tiktok-live scripts running automatically on an headless machine, if now I have to keep the cookies up to date, it will become much more complex to manage.
> 
> Do you know how many times I have changed cookies in the T1kt0k script since 2021? One time and only because I logged in from a new phone.
> 
> I don't want to discuss this anymore, no one is forcing you. You either offer your solution, or use or do not use what you have. This is exactly how Github works.

The fact that *you* had to change cookies only one time, it doesn't mean that everyone will have the same experience.

And even if they change only on a new login/logout, this is still much more complex than just download a live using a script that doesn't change. Not sure why you are denying this.

**Comment by booleangit** [comment]
> @roberto-sartori-gl @booleangit 
> 
>Do you really understand how this works? Or are you afraid of the word **cookies**? Can you identify if it's a human refreshing the page every 30 seconds or a script? If yes, tell me how you would got it? If not.
> 
> 

Wow, where does this hostility come from? I've even thanked you for posting the solution. I'm a C++ developer, so Python would definitely be a hobby language in comparison, but I'm not calling you a hobbyist, am I?

All I said is that because of the cookie, they now can easily identify which account is making the requests. In the previous situation (where you're just an anonymous user), they could only block your IP if you're hammering their servers with requests. Is that really so hard to understand?
