### ISSUE TITLE
Browser exec doesn't work

### ISSUE THREAD

**Issue by CyberbobGR** [roju/tiktok-live-recorder#23]
Installed chrome extension, logged in to tiktok, checked that the lives are visible on browser but still it doesn't work.
Tried multiple lives.

ttlr.py -mode auto -ffmpeg -combine -user ************ -browser_exec "C:\Program Files\Google\Chrome\Application\chrome.exe"
2024-02-02 03:45:23,263 - INFO - Tiktok Live Recorder v4.2
2024-02-02 03:45:24,299 - INFO - Username: ***********
2024-02-02 03:45:24,300 - INFO - Room ID: ************
2024-02-02 03:45:25,337 - INFO - *********** is live
2024-02-02 03:45:25,337 - INFO - Getting live url for room ID ****************
2024-02-02 03:45:25,903 - ERROR - Exception caught in main:
2024-02-02 03:45:25,904 - ERROR - Account is age restricted

Traceback (most recent call last):
  File "C:\tiktok-live-recorder-4.2\ttlr.py", line 97, in main
    bot.run()
  File "C:\tiktok-live-recorder-4.2\tiktok_bot.py", line 69, in run
    live_url = self.get_live_url()
               ^^^^^^^^^^^^^^^^^^^
  File "C:\tiktok-live-recorder-4.2\tiktok_bot.py", line 261, in get_live_url
    except errors.AgeRestricted as e: raise e
                                      ^^^^^^^
  File "C:\tiktok-live-recorder-4.2\tiktok_bot.py", line 249, in get_live_url
    if bot_utils.login_required(json):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tiktok-live-recorder-4.2\bot_utils.py", line 71, in login_required
    raise errors.AgeRestricted('Account is age restricted')
errors.AgeRestricted: Account is age restricted

**Comment by Sullyscharger** [comment]
Any update for this, not sure if I'm using the browser exec correctly or if it doesn't work on windows.

**Comment by L000CK3D** [comment]
> Installed chrome extension, logged in to tiktok, checked that the lives are visible on browser but still it doesn't work. Tried multiple lives.
> 
> ttlr.py -mode auto -ffmpeg -combine -user ************ -browser_exec "C:\Program Files\Google\Chrome\Application\chrome.exe" 2024-02-02 03:45:23,263 - INFO - Tiktok Live Recorder v4.2 2024-02-02 03:45:24,299 - INFO - Username: *********** 2024-02-02 03:45:24,300 - INFO - Room ID: ************ 2024-02-02 03:45:25,337 - INFO - *********** is live 2024-02-02 03:45:25,337 - INFO - Getting live url for room ID **************** 2024-02-02 03:45:25,903 - ERROR - Exception caught in main: 2024-02-02 03:45:25,904 - ERROR - Account is age restricted
> 
> Traceback (most recent call last): File "C:\tiktok-live-recorder-4.2\ttlr.py", line 97, in main bot.run() File "C:\tiktok-live-recorder-4.2\tiktok_bot.py", line 69, in run live_url = self.get_live_url() ^^^^^^^^^^^^^^^^^^^ File "C:\tiktok-live-recorder-4.2\tiktok_bot.py", line 261, in get_live_url except errors.AgeRestricted as e: raise e ^^^^^^^ File "C:\tiktok-live-recorder-4.2\tiktok_bot.py", line 249, in get_live_url if bot_utils.login_required(json): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\tiktok-live-recorder-4.2\bot_utils.py", line 71, in login_required raise errors.AgeRestricted('Account is age restricted') errors.AgeRestricted: Account is age restricted

i think that a private live is different to a age restricted live, a private live needs a permission of the host to acess and the age restricted live needs a account logged to see, to solve this error i think that we need to implement a new function to read cookies, if i was wrong please correct me (not sure if the extension take the cookies)
